[package]
name = "monkeycfmt"
version = "0.1.0"
edition = "2024"

[dependencies]
tree-sitter = {version = "0.25.9", features = ["std"] }
tree-sitter-monkeyc = {path="../tree-sitter-monkeyc"}

[build-dependencies]
cc = "1.2.37"
